name: Build Docker

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: "ubuntu-latest"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to registry
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: interstellarkai/wallstreetai:latest
                  dockerfile: ./Dockerfile

        steps:
        # need checkout before using compose-action
        - uses: actions/checkout@v3
        - uses: isbang/compose-action@v1.1.0
            with:
            compose-file: "./docker/docker-compose.yml"
            down-flags: "--volumes"
            services: |
                helloworld2
                helloworld3